#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;
#if defined(__cplusplus)
extern "C" {
#endif

extern void _AMPA_reg(void);
extern void _AMPA_stp_reg(void);
extern void _AMPA_test_reg(void);
extern void _Im_reg(void);
extern void _NMDA_reg(void);
extern void _NMDA_stp_reg(void);
extern void _NMDA_test_reg(void);
extern void _NMDAe_reg(void);
extern void _adaptive_AMPA_reg(void);
extern void _adaptive_NMDA_reg(void);
extern void _adaptive_NMDAe_reg(void);
extern void _adaptive_cshom_AMPA_reg(void);
extern void _adaptive_cshom_NMDA_reg(void);
extern void _adaptive_glutamate_reg(void);
extern void _adaptive_glutamate_cshom_reg(void);
extern void _adaptive_glutamate_hom_reg(void);
extern void _adaptive_glutamate_shom_reg(void);
extern void _adaptive_glutamate_test_reg(void);
extern void _adaptive_hom_AMPA_reg(void);
extern void _adaptive_hom_NMDA_reg(void);
extern void _adaptive_my_shom_NMDA_reg(void);
extern void _adaptive_pf_AMPA_reg(void);
extern void _adaptive_pf_NMDA_reg(void);
extern void _adaptive_sAMPA_reg(void);
extern void _adaptive_sNMDA_reg(void);
extern void _adaptive_sglutamate_reg(void);
extern void _adaptive_shom_AMPA_reg(void);
extern void _adaptive_shom_AMPA_stp_reg(void);
extern void _adaptive_shom_NMDA_reg(void);
extern void _adaptive_shom_NMDA_stp_reg(void);
extern void _adaptive_thalamus_reg(void);
extern void _adaptive_zahra_AMPA_reg(void);
extern void _adaptive_zahra_NMDA_reg(void);
extern void _bk_reg(void);
extern void _cadyn_reg(void);
extern void _cadyn_nmda_reg(void);
extern void _cal12_reg(void);
extern void _cal13_reg(void);
extern void _caldyn_reg(void);
extern void _can_reg(void);
extern void _caq_reg(void);
extern void _car_reg(void);
extern void _cat32_reg(void);
extern void _cat33_reg(void);
extern void _catdyn_reg(void);
extern void _cav32_reg(void);
extern void _cav33_reg(void);
extern void _exglu_reg(void);
extern void _gaba_reg(void);
extern void _gigr_reg(void);
extern void _glutamate_reg(void);
extern void _glutamate_ica_nmda_reg(void);
extern void _glutamate_sat_reg(void);
extern void _inhexp2syn_reg(void);
extern void _inhexpsyn_reg(void);
extern void _kaf_reg(void);
extern void _kas_reg(void);
extern void _kdr_reg(void);
extern void _kir_reg(void);
extern void _naf_reg(void);
extern void _ncx_reg(void);
extern void _pregen_reg(void);
extern void _sk_reg(void);
extern void _tmglut_reg(void);
extern void _vecevent_reg(void);

void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"AMPA.mod\"");
    fprintf(stderr, " \"AMPA_stp.mod\"");
    fprintf(stderr, " \"AMPA_test.mod\"");
    fprintf(stderr, " \"Im.mod\"");
    fprintf(stderr, " \"NMDA.mod\"");
    fprintf(stderr, " \"NMDA_stp.mod\"");
    fprintf(stderr, " \"NMDA_test.mod\"");
    fprintf(stderr, " \"NMDAe.mod\"");
    fprintf(stderr, " \"adaptive_AMPA.mod\"");
    fprintf(stderr, " \"adaptive_NMDA.mod\"");
    fprintf(stderr, " \"adaptive_NMDAe.mod\"");
    fprintf(stderr, " \"adaptive_cshom_AMPA.mod\"");
    fprintf(stderr, " \"adaptive_cshom_NMDA.mod\"");
    fprintf(stderr, " \"adaptive_glutamate.mod\"");
    fprintf(stderr, " \"adaptive_glutamate_cshom.mod\"");
    fprintf(stderr, " \"adaptive_glutamate_hom.mod\"");
    fprintf(stderr, " \"adaptive_glutamate_shom.mod\"");
    fprintf(stderr, " \"adaptive_glutamate_test.mod\"");
    fprintf(stderr, " \"adaptive_hom_AMPA.mod\"");
    fprintf(stderr, " \"adaptive_hom_NMDA.mod\"");
    fprintf(stderr, " \"adaptive_my_shom_NMDA.mod\"");
    fprintf(stderr, " \"adaptive_pf_AMPA.mod\"");
    fprintf(stderr, " \"adaptive_pf_NMDA.mod\"");
    fprintf(stderr, " \"adaptive_sAMPA.mod\"");
    fprintf(stderr, " \"adaptive_sNMDA.mod\"");
    fprintf(stderr, " \"adaptive_sglutamate.mod\"");
    fprintf(stderr, " \"adaptive_shom_AMPA.mod\"");
    fprintf(stderr, " \"adaptive_shom_AMPA_stp.mod\"");
    fprintf(stderr, " \"adaptive_shom_NMDA.mod\"");
    fprintf(stderr, " \"adaptive_shom_NMDA_stp.mod\"");
    fprintf(stderr, " \"adaptive_thalamus.mod\"");
    fprintf(stderr, " \"adaptive_zahra_AMPA.mod\"");
    fprintf(stderr, " \"adaptive_zahra_NMDA.mod\"");
    fprintf(stderr, " \"bk.mod\"");
    fprintf(stderr, " \"cadyn.mod\"");
    fprintf(stderr, " \"cadyn_nmda.mod\"");
    fprintf(stderr, " \"cal12.mod\"");
    fprintf(stderr, " \"cal13.mod\"");
    fprintf(stderr, " \"caldyn.mod\"");
    fprintf(stderr, " \"can.mod\"");
    fprintf(stderr, " \"caq.mod\"");
    fprintf(stderr, " \"car.mod\"");
    fprintf(stderr, " \"cat32.mod\"");
    fprintf(stderr, " \"cat33.mod\"");
    fprintf(stderr, " \"catdyn.mod\"");
    fprintf(stderr, " \"cav32.mod\"");
    fprintf(stderr, " \"cav33.mod\"");
    fprintf(stderr, " \"exglu.mod\"");
    fprintf(stderr, " \"gaba.mod\"");
    fprintf(stderr, " \"gigr.mod\"");
    fprintf(stderr, " \"glutamate.mod\"");
    fprintf(stderr, " \"glutamate_ica_nmda.mod\"");
    fprintf(stderr, " \"glutamate_sat.mod\"");
    fprintf(stderr, " \"inhexp2syn.mod\"");
    fprintf(stderr, " \"inhexpsyn.mod\"");
    fprintf(stderr, " \"kaf.mod\"");
    fprintf(stderr, " \"kas.mod\"");
    fprintf(stderr, " \"kdr.mod\"");
    fprintf(stderr, " \"kir.mod\"");
    fprintf(stderr, " \"naf.mod\"");
    fprintf(stderr, " \"ncx.mod\"");
    fprintf(stderr, " \"pregen.mod\"");
    fprintf(stderr, " \"sk.mod\"");
    fprintf(stderr, " \"tmglut.mod\"");
    fprintf(stderr, " \"vecevent.mod\"");
    fprintf(stderr, "\n");
  }
  _AMPA_reg();
  _AMPA_stp_reg();
  _AMPA_test_reg();
  _Im_reg();
  _NMDA_reg();
  _NMDA_stp_reg();
  _NMDA_test_reg();
  _NMDAe_reg();
  _adaptive_AMPA_reg();
  _adaptive_NMDA_reg();
  _adaptive_NMDAe_reg();
  _adaptive_cshom_AMPA_reg();
  _adaptive_cshom_NMDA_reg();
  _adaptive_glutamate_reg();
  _adaptive_glutamate_cshom_reg();
  _adaptive_glutamate_hom_reg();
  _adaptive_glutamate_shom_reg();
  _adaptive_glutamate_test_reg();
  _adaptive_hom_AMPA_reg();
  _adaptive_hom_NMDA_reg();
  _adaptive_my_shom_NMDA_reg();
  _adaptive_pf_AMPA_reg();
  _adaptive_pf_NMDA_reg();
  _adaptive_sAMPA_reg();
  _adaptive_sNMDA_reg();
  _adaptive_sglutamate_reg();
  _adaptive_shom_AMPA_reg();
  _adaptive_shom_AMPA_stp_reg();
  _adaptive_shom_NMDA_reg();
  _adaptive_shom_NMDA_stp_reg();
  _adaptive_thalamus_reg();
  _adaptive_zahra_AMPA_reg();
  _adaptive_zahra_NMDA_reg();
  _bk_reg();
  _cadyn_reg();
  _cadyn_nmda_reg();
  _cal12_reg();
  _cal13_reg();
  _caldyn_reg();
  _can_reg();
  _caq_reg();
  _car_reg();
  _cat32_reg();
  _cat33_reg();
  _catdyn_reg();
  _cav32_reg();
  _cav33_reg();
  _exglu_reg();
  _gaba_reg();
  _gigr_reg();
  _glutamate_reg();
  _glutamate_ica_nmda_reg();
  _glutamate_sat_reg();
  _inhexp2syn_reg();
  _inhexpsyn_reg();
  _kaf_reg();
  _kas_reg();
  _kdr_reg();
  _kir_reg();
  _naf_reg();
  _ncx_reg();
  _pregen_reg();
  _sk_reg();
  _tmglut_reg();
  _vecevent_reg();
}

#if defined(__cplusplus)
}
#endif
